---
- name: Install Neovim
  shell: "cd {{ USER_DIR }} && curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage && chmod u+x nvim.appimage && ./nvim.appimage --appimage-extract && ./squashfs-root/AppRun --version && sudo mv squashfs-root / && sudo ln -s /squashfs-root/AppRun /usr/bin/nvim"

- name: Remove Neovim installer
  file:
    path: "{{ USER_DIR }}/nvim.appimage"
    state: absent

- name: Install NvChad
  shell: "cd {{ USER_DIR }} && git clone https://github.com/NvChad/starter .config/nvim && chown -R {{ USER }} .config/nvim && mkdir -p /root/.config/nvim && cp -r {{ USER_DIR }}/.config/nvim /root/.config/nvim"
