---
- name: Install JDK 21
  apt:
    name: openjdk-21-jdk
    state: latest

- name: Remove BurpSuite
  apt:
    name: burpsuite
    state: absent

- name: Copy BurpSuite
  copy:
    src: "../files/burpsuite"
    dest: "/usr/share"
    owner: root
    group: root

- name: Set execution permission to BurpSuite
  file:
    path: "/usr/share/burpsuite/burpsuite"
    mode: '0755'

- name: Make BurpSuite symlink to /usr/bin
  file:
    src: "/usr/share/burpsuite/burpsuite"
    dest: "/usr/bin/burpsuite"
    state: link

- name: Create JDK Config for BurpSuite
  file:
    path: "{{ USER_DIR }}/.java/.userPrefs"
    state: directory

- name: Copy BurpSuite Config
  copy:
    src: "../files/burp"
    dest: "{{ USER_DIR }}/.java/.userPrefs"
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: '0775'
