---
- name: Clone Picom repository
  git:
    repo: https://github.com/ibhagwan/picom.git
    dest: "{{ USER_DIR }}/github/picom"
    clone: yes
    recursive: no

- name: Install Picom
  shell: "cd {{ USER_DIR }}/github/picom && git submodule update --init --recursive && meson --buildtype=release . build && ninja -C build && ninja -C build install"

- name: Copy Picom config
  copy:
    src: "../files/picom"
    dest: "{{ USER_DIR }}/.config"
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: '0644'
