---
- name: Clone p10k repository
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ USER_DIR }}/.powerlevel10k"
    clone: yes
    depth: 1
    recursive: no

- name: Change p10k repository permissions
  file:
    path: "{{ USER_DIR }}/.powerlevel10k"
    state: directory
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Copy .p10k.zsh user
  copy:
    src: "../files/user/.p10k.zsh"
    dest: "{{ USER_DIR }}"
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: '0755'

- name: Copy .p10k.zsh root
  copy:
    src: "../files/root/.p10k.zsh"
    dest: "/root"
    owner: root
    group: root
    mode: '0755'
