---
- name: Clone Polybar repository
  git:
    repo: https://github.com/polybar/polybar.git
    dest: "{{ USER_DIR }}/github/polybar"
    clone: yes
    recursive: yes

- name: Install Polybar
  shell: "cd {{ USER_DIR }}/github/polybar && mkdir build && cd build && cmake .. && make -j$(nproc) && make install"

- name: Copy Polybar fonts
  copy:
    src: "../files/truetype"
    dest: "/usr/share/fonts"

- name: Copy Polybar scripts
  copy:
    src: "../files/bin"
    dest: "{{ USER_DIR }}/.config"
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: '0755'

- name: Copy Polybar config
  copy:
    src: "../files/polybar"
    dest: "{{ USER_DIR }}/.config"
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: '0755'
